/**
 * Lista de escolas para os filtros e formulários da biblioteca.
 * Ordem alinhada com a base das escolas (sem "Todas as escolas").
 */
export const LISTA_ESCOLAS = [
    'Escola Secundária Marques de Castilho',
    'Escola Secundária José Estêvão',
    'EB Dr. João Rocha - Pai',
    'ES de Vagos',
    'Agrupamento de Escolas Afonso de Paiva',
    'Escola Básica Cidade de Castelo Branco',
    'Escola Básica de São Vicente da Beira',
    'Escola Básica e Secundária de Alcains',
    'Escola Básica Prof. Dr. António Sena Faria de Vasconcelos',
    'Escola Secundária Nuno Álvares',
    'Escola Básica de São Domingos',
    'Escola Básica de Tortosendo',
    'Escola Básica n.º 2 de Paul',
    'Escola Básica n.º 2 de Teixoso',
    'Escola Básica Pero da Covilhã',
    'Escola Secundária Campos de Melo',
    'Escola Secundária Frei Heitor Pinto',
    'Escola Secundária Quinta das Palmeiras',
    'Escola Secundária do Fundão',
    'Escola Básica e Secundária José Silvestre Ribeiro',
    'Escola Básica e Secundária Pe. António de Andrade',
    'Escola Básica e Secundária Ribeiro Sanches',
    'Escola Básica e Secundária Pedro da Fonseca',
    'Escola Básica de Sertã',
    'Escola Básica Padre António Lourenço Farinha',
    'Escola Básica São Nuno de Santa Maria',
    'Escola Secundária de Sertã',
    'Escola Básica de Vila Velha de Ródão',
    'Escola Básica Carlos de Oliveira',
    'Escola Básica e Secundária João Garcia Bacelar',
    'Escola Básica de Ceira',
    'Escola Básica Eugénio de Castro',
    // \u00E1 garante «á» correcto mesmo com encoding estranho no ficheiro / bundler.
    'Escola Secund\u00E1ria Avelar Brotero',
] as const;
