type User @table {
  username: String!
  email: String!
  createdAt: Timestamp!
  displayName: String
  bio: String
  profilePictureUrl: String
}

type Book @table {
  title: String!
  author: String!
  publicationYear: Int!
  createdAt: Timestamp!
  summary: String
  genres: [String]
  isbn: String
  coverImageUrl: String
}

type ReadingStatus @table {
  user: User!
  book: Book!
  status: String!
  createdAt: Timestamp!
  startedReadingAt: Timestamp
  finishedReadingAt: Timestamp
}

type Review @table {
  user: User!
  book: Book!
  readingStatus: ReadingStatus
  rating: Int!
  createdAt: Timestamp!
  isPublic: Boolean!
  reviewText: String
  updatedAt: Timestamp
}

type BookList @table {
  user: User!
  name: String!
  isPublic: Boolean!
  createdAt: Timestamp!
  description: String
  updatedAt: Timestamp
}

type BookListItem @table(key: ["bookList", "book"]) {
  bookList: BookList!
  book: Book!
  position: Int!
  addedAt: Timestamp!
  note: String
}